# Config file for jarvis-quality-air-france plugin

# Default city, must be one of the following cities.
# They can also be picked up one this map: http://www.prevair.org/
pg_aq_france_city="Grenoble"

#    - AGDE
#    - AGEN
#    - AIX-EN-PROVENCE
#    - AJACCIO
#    - ALBERTVILLE
#    - ALBI
#    - ALENCON
#    - ALES
#    - AMIENS
#    - ANGERS
#    - ANNECY
#    - ANNEMASSE
#    - ARCACHON
#    - ARRAS
#    - AURILLAC
#    - AVIGNON
#    - BASTIA
#    - BAYONNE
#    - BELESTA-EN-LAURAGAIS
#    - BELFORT
#    - BESANCON
#    - BETHUNE
#    - BEZIERS
#    - BLOIS
#    - BORDEAUX
#    - BOULOGNE-SUR-MER
#    - BOURG-EN-BRESSE
#    - BOURGES
#    - BOURGOIN-JALLIEU
#    - BREST
#    - CAEN
#    - CALAIS
#    - CANNES
#    - CASTRES
#    - CHALONS-EN-CHAMPAGNE
#    - CHAMBERY
#    - CHAMONIX-MONT-BLANC
#    - CHARLEVILLE-MEZIERES
#    - CHARTRES
#    - CHATEAUROUX
#    - CHERBOURG-OCTEVILLE
#    - CHOLET
#    - CLERMONT-FERRAND
#    - COLMAR
#    - Commune
#    - CREIL
#    - DAX
#    - DOLE
#    - DREUX
#    - DUNKERQUE
#    - EVREUX
#    - FIGEAC
#    - FORBACH
#    - FORT-DE-FRANCE
#    - FOUGERES
#    - GRANDFONTAINE
#    - GRENOBLE
#    - ISSOIRE
#    - LACQ
#    - (LA)PETITE-PIERRE
#    - (LA)ROCHE-SUR-YON
#    - LAVAL
#    - (LE)HAVRE
#    - (LE)MANS
#    - LENS
#    - (LE)PUY-EN-VELAY
#    - LILLE
#    - LISIEUX
#    - LONS-LE-SAUNIER
#    - LORIENT
#    - LOURDES
#    - LYON
#    - MARSEILLE
#    - MAUBEUGE
#    - METZ
#    - MONTARGIS
#    - MONTAUBAN
#    - MONTBELIARD
#    - MONTLUCON
#    - MONTPELLIER
#    - MOULINS
#    - MULHOUSE
#    - MUNCHHAUSEN
#    - NANCY
#    - NANTES
#    - NICE
#    - NIMES
#    - ORLEANS
#    - PARIS
#    - PASSY
#    - PAU
#    - PERIGUEUX
#    - PERPIGNAN
#    - POINTE-A-PITRE
#    - REIMS
#    - RENNES
#    - RIOM
#    - ROANNE
#    - RODEZ
#    - ROMANS-SUR-ISERE
#    - ROUEN
#    - SAINT-BRIEUC
#    - SAINT-DENIS
#    - SAINT-DIZIER
#    - SAINT-ETIENNE
#    - SAINT-JEAN-DE-MAURIENNE
#    - SAINT-LAURENT-DES-ARBRES
#    - SAINT-LO
#    - SAINT-MALO
#    - SAINT-NAZAIRE
#    - SAINT-OMER
#    - SAINT-PAUL
#    - SAINT-PIERRE
#    - SAINT-QUENTIN
#    - STRASBOURG
#    - TARBES
#    - THIONVILLE
#    - TOULON
#    - TOULOUSE
#    - TOURS
#    - TROYES
#    - VALENCE
#    - VALENCIENNES
#    - VANNES
#    - VENACO
#    - VESOUL
#    - VIENNE
#    - VIERZON
#    - VILLAGE-NEUF
